"""empty message

Revision ID: 33fc93b19b6e
Revises: 
Create Date: 2024-09-15 22:30:09.455269

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33fc93b19b6e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
